name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        run: |
          PYTHON_VERSION="3.12.0-rc.1"
          DOWNLOAD_URL="https://github.com/actions/python-versions/releases/download/${PYTHON_VERSION}-5785015073/python-${PYTHON_VERSION}-linux-20.04-x64.tar.gz"
          
          mkdir -p $RUNNER_TOOL_CACHE/Python/$PYTHON_VERSION/x64
          curl -L -o python.tar.gz $DOWNLOAD_URL
          tar -xzf python.tar.gz -C $RUNNER_TOOL_CACHE/Python/$PYTHON_VERSION/x64 --strip-components=1
          rm python.tar.gz
      - name: Install dependencies
        run: pip install -r requirements.txt 
      - name: Run Tests
        run: python -m pytest
